const PAPEL_NUTRICIONISTA_NOME = 'NUTRICIONISTA'

const TOKEN_OBRIGATORIO = 'O token é obrigatório para esta operação.'
const TOKEN_INVALIDO = 'Token inválido.'
const TOKEN_TEMPO_VALIDO = 60 * 60 * 24 * 7

module.exports = {
  PAPEL_NUTRICIONISTA_NOME, TOKEN_OBRIGATORIO, TOKEN_INVALIDO, TOKEN_TEMPO_VALIDO
}